config/routes.rb
LibeautyCrm::Application.routes.draw do
  resources :tasks

  devise_for :users
  resources :evaluations
  resources :comments
  resources :accounts do
    collection { post :import }
  end

  root 'dashboard#index'

  resources :settings, only: [:index] do
    collection do
      get 'category'
      get 'account'
      get 'evaluation'
    end
  end
  
  resources :categories
  resources :field_groups
  resources :fields

  

end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  has_many :field_details, dependent: :destroy
  belongs_to :category
  belongs_to :account
  belongs_to :user
  
  accepts_nested_attributes_for :field_details, allow_destroy: true
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :set_evaluation, only: [:show, :edit, :update, :destroy]
  after_filter :update_score, only: [:update]

  # GET /evaluations
  # GET /evaluations.json
  def index
    @evaluations = Evaluation.all
  end

  # GET /evaluations/1
  # GET /evaluations/1.json
  def show
  end

  # GET /evaluations/new
  def new
    @evaluation = Evaluation.new
  end

  # GET /evaluations/1/edit
  def edit
  end

  # POST /evaluations
  # POST /evaluations.json
  def create
    @evaluation = Evaluation.new(evaluation_params)
    add_user_id(@evaluation)
    respond_to do |format|
      if @evaluation.save
        field_groups = @evaluation.category.field_groups
        field_groups.each do |fg|
          fg.fields.each do |f|
            field_detail = @evaluation.field_details.create(field_id: f.id)
          end
        end
        format.html { redirect_to edit_evaluation_path(@evaluation), notice: 'Evaluation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @evaluation }
      else
        format.html { render action: 'new' }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1
  # PATCH/PUT /evaluations/1.json
  def update
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.html { redirect_to @evaluation.account, notice: 'Evaluation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1
  # DELETE /evaluations/1.json
  def destroy
    account = @evaluation.account
    @evaluation.destroy
    respond_to do |format|
      format.html { redirect_to account }
      format.json { head :no_content }
    end
  end

  def update_score
    sum = 0
    @evaluation.field_details.each do |f|
      sum =+ f.value.to_i
    end
    @evaluation.score = sum
    @evaluation.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = Evaluation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluation_params
      params.require(:evaluation).permit(:name, :account_id, :category_id, :score, field_details_attributes: [:id, :value])
    end
end

app/views/evaluations/_form.html.erb
<%= form_for(@evaluation) do |f| %>
  <% if @evaluation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evaluation.errors.count, "error") %> prohibited this evaluation from being saved:</h2>

      <ul>
      <% @evaluation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :account_id, :value => params[:account_id] || @evaluation.account_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %>
    <%= f.select :category_id, Category.where(category_class: "Evaluation").all.map{ |c| [c.name,c.id]} %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn" %>
  </div>
<% end %>

app/views/evaluations/edit.html.erb
<h2>Editing Evaluation</h2>

<%= render 'form' %>

<%= link_to 'Back', account_path(@evaluation.account) %>

<%= form_for(@evaluation) do |f|%>
  <% @evaluation.category.field_groups.each do |field_group| %>
     <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href=<%= "##{field_group.name}"%>>
          <%= field_group.name %>
          </a>
        </div>
        <div id="<%= field_group.name %>" class="accordion-body collapse in">
          <div class="accordion-inner">
            <fieldset>
              <table class="table table-hover">
                <thead>
                  <th>Name</th>
                  <th></th>
                  <th>Value</th>
                </thead>
                <%= f.fields_for :field_details do |field_detail| %>
                  <% if field_detail.object.field.field_group.id == field_group.id %>
                  <tr>
                    <td><%= field_detail.label field_detail.object.field.name %></td>
                    <td><div class="slider-range-min"></td>
                    <td>
                      </div><%= field_detail.text_field :value, class: "test" %>
                    </td>
                  </tr>
                  <% end %>
                <% end %>
              </table>
            </fieldset>
          </div>
        </div>
      </div>
  <% end %>
  <%= f.submit "save", class: "btn pull-right" %>
<% end %>

app/views/evaluations/index.html.erb
<h1>Listing evaluations</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Category</th>
      <th>Score</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluations.each do |evaluation| %>
      <tr>
        <td><%= evaluation.account_id %></td>
        <td><%= evaluation.category_id %></td>
        <td><%= evaluation.score %></td>
        <td><%= link_to 'Show', evaluation %></td>
        <td><%= link_to 'Edit', edit_evaluation_path(evaluation) %></td>
        <td><%= link_to 'Destroy', evaluation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evaluation', new_evaluation_path %>

app/views/evaluations/new.html.erb
<h1>New evaluation</h1>

<%= render 'form' %>

<%= link_to 'Back', evaluations_path %>

app/views/evaluations/show.html.erb
  

<p>
  <strong>Account:</strong>
  <%= @evaluation.account_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @evaluation.category_id %>
</p>

<p>
  <strong>Score:</strong>
  <%= @evaluation.score %>
</p>

<%= link_to 'Edit', edit_evaluation_path(@evaluation) %> |
<%= link_to 'Back', account_path(@evaluation.account) %>