config/routes.rb
LibeautyCrm::Application.routes.draw do
  resources :tasks

  devise_for :users
  resources :evaluations
  resources :comments
  resources :accounts do
    collection { post :import }
  end

  root 'dashboard#index'

  resources :settings, only: [:index] do
    collection do
      get 'category'
      get 'account'
      get 'evaluation'
    end
  end
  
  resources :categories
  resources :field_groups
  resources :fields

  

end

app/models/setting.rb
class Setting
  def self.sidebar
    return ["accounts","tasks","settings"]
  end

  def self.field_option
    return ["short","long","date","boolean","select-box"]
  end

  def self.setting_menu
    return ["category"]
  end

  def self.category_class
    return ["Account"]
    # return ["Account","Evaluation"]
  end

  def self.task_status
    return ["Pending","Assigned","Completed"]
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :set_active_menu
  def set_active_menu
    @menu_active = action_name
  end
  def index
    redirect_to category_settings_path
  end

  def category
    @categories = Category.all
  end

  def account

  end

  def evaluation
    
  end
end

app/views/settings/_menu.html.erb
<h2><%= titlelize(t(:setting)) %></h2>
<ul class="nav nav-tabs">
  <% Setting.setting_menu.each do |menu| %>
    <% if menu == @menu_active %>
      <li class="active"><%= link_to titlelize(menu), "#{menu}_settings".to_sym %></li>
    <% else %>
      <li><%= link_to titlelize(menu), "#{menu}_settings".to_sym %></li>
    <% end %>
  <% end %>
</ul>

app/views/settings/category.html.erb
<%= render partial: "menu" %>

<h2><%= t(:categories)%> <span class="pull-right"><%= link_to t(:new_category), new_category_path, class: "btn"%></span></h2>

<% Setting.category_class.each do |cate_class|%>
<strong><%= titlelize("#{cate_class} #{t(:category)}") %></strong>
<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th><%= t(:name)%></th>
      <th><%= t(:actions)%></th>
    </tr>
  </thead>
  <% @categories.where(category_class: cate_class).each_with_index do |ac,index| %>
    <tr>
      <td><%= index+1 %></td>
      <td><%= ac.name %></td>
      <td>
        <ul class="inline">
          <li><%= link_to t(:show), category_path(ac.id) %></li>
          <li><%= link_to t(:destroy), category_path(ac.id), method: "delete", data: { confirm: 'Are you sure ?' } %></li>
        </ul>
      </td>
    </tr>
  <% end %>
</table>
<% end %>

app/views/settings/index.html.erb
<%= render partial: "menu" %>