config/routes.rb
LibeautyCrm::Application.routes.draw do
  resources :tasks

  devise_for :users
  resources :evaluations
  resources :comments
  resources :accounts do
    collection { post :import }
  end

  root 'dashboard#index'

  resources :settings, only: [:index] do
    collection do
      get 'category'
      get 'account'
      get 'evaluation'
    end
  end
  
  resources :categories
  resources :field_groups
  resources :fields

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :field_groups, dependent: :destroy
  has_many :accounts, dependent: :destroy
  has_many :evaluations, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        @category.field_groups.create(name: "General")
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to category_settings_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :category_class)
    end
end

app/views/categories/_field_group.html.erb
<h4><%= titlelize(t(:field_group)) %></h4>
<%= form_for(FieldGroup.new) do |f| %>
  <fieldset>
    <div class="input-append pull-right">
      <%= f.text_field :name %>
      <%= f.hidden_field :category_id, :value => @category.id %>
      <%= f.submit "Create", class:"btn" %>
    </div>
  </fieldset>
<% end %>
<div class="accordion" id="accordion2">
  <% @category.field_groups.each do |fg| %>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href=<%= "##{fg.name}"%>>
        <%= fg.name %>
      </a>
    </div>
    <div id="<%= fg.name %>" class="accordion-body collapse in">
      <div class="accordion-inner">

        <%= render partial: "field_groups/field", locals: {field_group: fg} %>
        <hr>
        <p class="text-right">
          <%= link_to t(:destroy_field_group), fg, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :class %>
  <%= f.select :category_class, Setting.category_class %>
  <div class="actions">
    <%= f.submit class: "btn" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render partial: "settings/menu" %>
<h2><%= t(:edit_category) %></h2>

<%= render 'form' %>

<%= link_to t(:show), @category %> |
<%= link_to t(:back), @category %>

app/views/categories/new.html.erb
<%= render partial: "settings/menu" %>
<h2><%= t(:new_category) %></h2>

<%= render 'form' %>

<%= link_to t(:back), category_settings_path %>

app/views/categories/show.html.erb
<%= render partial: "settings/menu" %>
  

<h4><%= titlelize("#{@category.category_class} / #{t(:category)} / #{@category.name}") %></h4>
<%= link_to t(:edit), edit_category_path(@category) %> |
<%= link_to t(:back), category_settings_path %>
<hr>
<%= render partial: "field_group" %>