config/routes.rb
LibeautyCrm::Application.routes.draw do
  resources :tasks

  devise_for :users
  resources :evaluations
  resources :comments
  resources :accounts do
    collection { post :import }
  end

  root 'dashboard#index'

  resources :settings, only: [:index] do
    collection do
      get 'category'
      get 'account'
      get 'evaluation'
    end
  end
  
  resources :categories
  resources :field_groups
  resources :fields

  

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :category
  has_many :field_details, dependent: :destroy
  has_many :evaluations, dependent: :destroy
  belongs_to :user
  
  accepts_nested_attributes_for :field_details, allow_destroy: true

  acts_as_commentable

  

  def field_detail(field_id)
    FieldDetail.find_by_account_id_and_field_id(id,field_id)
  end

  def all_fields
    return self.field_details.map{ |field_detail| {field_detail.field.name => field_detail.value}}
  end 

  def categories
    return Category.where(category_class: "Account").all.map{ |c| [c.name,c.id]}
  end 

  def header_fields
    return Account.column_names + self.all_fields.map{|h| h.keys[0]}
  end

  def all_fields_value
    custom_field_values = self.all_fields
    field_values = self.attributes
    custom_field_values.each do |field|
      field_values.merge!(field)
    end
    return field_values
  end

  def self.to_csv(accounts)
    CSV.generate do |csv|
      header = accounts.first.header_fields
      csv << header
      accounts.each do |account|
        modified_values = account.all_fields_value
        modified_values["category_id"] = Category.find_by_id(modified_values["category_id"]).name
        modified_values["user_id"] = User.find_by_id(modified_values["user_id"]).username
        csv << modified_values.values_at(*header)
      end
    end
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      
      row = Hash[[header, spreadsheet.row(i)].transpose]
      row["category_id"] = Category.find_by_name(row["category_id"]).id
      row["user_id"] = User.find_by_username(row["user_id"]).id
      attributes = Hash.new
      row.keys.each do |key|
        Account.column_names.each do |c_name|
          if key == c_name
            attributes.merge!({key => row[key]})
            row.delete(key)
          end
        end
      end

      if account = Account.find_by_id(attributes["id"])
        account.update_attributes(attributes)
      else  
        account = Account.create(attributes)
      end

      field_groups = account.category.field_groups
      field_groups.each do |fg|
        fg.fields.each do |f|
          field_detail = account.field_details.find_by_field_id(f.id) || account.field_details.new(field_id: f.id)
          field_detail.attributes = {value: row[f.name]}
          field_detail.save
        end
      end
      
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path) 
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :new_account, only: [:index, :new, :create]
  
  
  # GET /accounts
  # GET /accounts.json
  def import
    Account.import(params[:file])
    redirect_to root_url, notice: "Products imported."
  end

  def index
    if params[:task] == "search"
      if params[:name].present?
        accounts = Account.where("name like ? and category_id = ?", "%#{params[:name]}%", params[:category_id].to_i)
      else
        accounts = Account.where(category_id: params[:category_id])
      end
      @accounts = accounts.map{ |account| {id: account.id, name: account.name, username: account.user.username, created_at: account.created_at.to_date.to_s(:long)}}
    else
      @accounts = Hash.new
      Category.where(category_class: "Account").each do |category|
        @accounts.merge!(category.name.to_sym => category.accounts.last(20)) 
      end
    end
    
    respond_to do |format|
      format.html
      format.js { render :json => @accounts }
      format.csv { send_data Account.to_csv(@accounts[params[:category].to_sym]) }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    add_user_id(@account)
    respond_to do |format|
      if @account.save
        field_groups = @account.category.field_groups
        field_groups.each do |fg|
          fg.fields.each do |f|
            field_detail = @account.field_details.create(field_id: f.id)
          end
        end

        format.html { redirect_to edit_account_path(@account, alert_type: 'alert alert-success'), notice: 'Account was successfully created.' }
        format.json { render action: 'show', status: :created, location: @account }
      else
        format.html { render action: 'new' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    def new_account
      @account = Account.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:file, :name, :category_id, field_details_attributes: [:id, :value])
    end


end

app/views/accounts/_evaluation.html.erb
<% @account.evaluations.each do |evaluation| %> 
  <h5><%= "#{evaluation.category.name} ##{evaluation.id}" %></h5>
  <p class="text-right">
    <%= link_to t(:edit), edit_evaluation_path(evaluation) %> | 
    <%= link_to t(:destroy), evaluation, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
  <div class="accordion" id="Evaluation">
    <% evaluation.category.field_groups.each do |fg| %>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#Evaluation" href=<%= "#Evaluation#{fg.name}"%>>
          <%= "#{fg.name}" %>
        </a>
      </div>
      <div id="<%= "Evaluation#{fg.name}" %>" class="accordion-body collapse in">
        <div class="accordion-inner">
          <table class="table table-hover">
            <thead>
              <th>#</th>
              <th><%= t(:name) %></th>
              <th><%= t(:value) %></th>
            </thead>
            <% fg.fields.each_with_index do |f,index| %>
              <tr>
                <td><%= index+1%></td>
                <td><%= f.name %></td>
                <td><%= FieldDetail.find_by_evaluation_id_and_field_id(evaluation.id,f.id).try(:value) %></td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
    <% end %>
  </div>
<% end %>

app/views/accounts/_field_group.html.erb
<div class="accordion" id="accordion2">
  <% @account.category.field_groups.each do |fg| %>
  <div class="accordion-group no-border">
    <div class="accordion-heading accordion-heading-border">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href=<%= "##{fg.name}"%>>
        <%= fg.name %>
      </a>
    </div>
    <div id="<%= fg.name %>" class="accordion-body collapse in">
      <div class="accordion-inner no-border">
        <table class="table table-hover">
          <thead>
            <th>#</th>
            <th><%= t(:name) %></th>
            <th><%= t(:value) %></th>
          </thead>
          <% fg.fields.each_with_index do |f,index| %>
            <tr>
              <td><%= index+1%></td>
              <td><%= f.name %></td>
              <td><%= @account.field_detail(f.id).try(:value) %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <table class="table">
    <thead>
      <th>Name</th>
      <th>Value</th>
    </thead>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td><%= f.label :category %></td>
      <td><%= f.select :category_id, @account.categories %></td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit class: "btn" %></td>
    </tr> 
  </table>
<% end %>

app/views/accounts/_import.html.erb
<%= form_tag import_accounts_path, multipart: true do %>
  <%= file_field_tag :file, class: "" %><br><br>
  <%= submit_tag "Import", class: "btn" %>
<% end %>

app/views/accounts/_table.html.erb
<table class="table table-hover">
  <thead>
    <th>
      <% if accounts.first.present? %>
      <input id="search<%= accounts.first.category.name %>"class="searchByName" data-category="<%= accounts.first.category.id %>" type="text" placeholder="Search by Name"> <i>at least 3 letters</i><br>
      <b><%= "#{accounts.first.category.name} Lists" %></b>
      <% end %>
    </th>
  </thead>
  <tbody>
  <% accounts.each do |account| %>
    <tr>
      <td>
        <i><%= "##{account.id}"%></i>
        <b> <%= link_to account.name, account_path(account) %> </b>
        <i>created by </i>
        <b><a><%= account.user.username %></a></b>,
        <i> <%= account.created_at.to_date.to_s(:long)%></i>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/accounts/edit.html.erb
<h2>Editing account</h2>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

<h3><%= t(:field_group) %></h3>
<%= form_for(@account) do |f|%>
  <% @account.category.field_groups.each do |field_group| %>
     <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href=<%= "##{field_group.name}"%>>
          <%= field_group.name %>
          </a>
        </div>
        <div id="<%= field_group.name %>" class="accordion-body collapse in">
          <div class="accordion-inner">
            <fieldset>
              <table class="table table-hover">
                <thead>
                  <th>Name</th>
                  <th>Value</th>
                </thead>
                <%= f.fields_for :field_details do |field_detail| %>
                  <% if field_detail.object.field.field_group.id == field_group.id %>
                  <tr>
                    <td><%= field_detail.label field_detail.object.field.name %></td>
                    <% if field_detail.object.field.type == "date" %>
                      <td><%= field_detail.text_field :value, class: "datepicker" %></td>
                    <% elsif field_detail.object.field.type == "long" %>
                      <td><%= field_detail.text_area :value %></td>
                    <% elsif field_detail.object.field.type == "boolean" %>
                      <td><%= field_detail.check_box :value %></td>
                    <% elsif field_detail.object.field.type == "select-box" %>
                      <% collection = field_detail.object.field.option.split(",") %>
                      <td><%= field_detail.select :value, collection %></td>
                    <% else %>
                      <td><%= field_detail.text_field :value %></td>
                    <% end %>
                  </tr>
                  <% end %>
                <% end %>
              </table>
            </fieldset>
          </div>
        </div>
      </div>
  <% end %>
  <%= f.submit "save", class: "btn pull-right" %>
<% end %>

app/views/accounts/index.html.erb
<h3><%= titlelize(t(:account)).pluralize %></h3>

<ul class="nav nav-tabs" id="accountCategories">
  <% @accounts.keys.each.each_with_index do |key,index| %>
    <% index == 0 ? style = "active" : style = ""%>
    <li class="<%= style %>"><a href=<%="##{key.to_s.downcase}"%>><%= key.to_s %></a></li>
  <% end %>
  <li><a href="#importAccount"%>Import Accounts</a></li>
  <li><a href="#createAccount"%>Create Account</a></li>
</ul>
<div class="tab-content">
  <% @accounts.keys.each_with_index do |key,index| %>
    <% index == 0 ? style = "active" : style = ""%>
    <div class="tab-pane <%= style %>" id="<%= key.to_s.downcase %>">
      <%= render partial: "accounts/table", locals: {accounts: @accounts[key]} %>
      Export - <%= link_to "CSV", accounts_path(format: :csv, category: key)%>
    </div>
    <div class="tab-pane" id="importAccount">
      <%= render "accounts/import" %>
    </div>
    <div class="tab-pane" id="createAccount">
      <%= render "accounts/form" %>
    </div>
  <% end %>
</div>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
  
<h3><%= "#{@account.category.name} #{@account.name} ##{@account.id}"%></h3>

<ul class="nav nav-tabs" id="accountCategories">
  <li class="active"><a href="#details"%>Details</a></li>
  <!-- <li><a href="#evaluations"%>Evaluations</a></li> -->
  <li><a href="#comments"%>Comments</a></li>
  <li><%= link_to "Edit", edit_account_path(@account) %></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="details">
    <%= render "field_group" %>
  </div>
  <div class="tab-pane" id="evaluations">
    <%= link_to t(:create), new_evaluation_path(account_id: @account.id) %>
    <%= render "evaluation" %>
  </div>
  <div class="tab-pane" id="comments">
    <%= render partial: "shared/comment", locals: {asset: @account} %>
  </div>
</div>